# SERVER
server.port=${PORT:8080}

# SPRING APP
spring.application.name=api-gateway

# =========================
# GATEWAY CORS CONFIG
# =========================
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200,https://quantity-measurement-app-frontend-vert.vercel.app
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=3600

# =========================
# DISABLE DISCOVERY LOCATOR
# =========================
spring.cloud.gateway.discovery.locator.enabled=false

eureka.client.enabled=true
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=https://eureka-service-production-5bd5.up.railway.app/eureka/
eureka.instance.prefer-ip-address=true

# =========================
# ROUTES
# =========================

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# OAuth2
spring.cloud.gateway.routes[1].id=auth-oauth2
spring.cloud.gateway.routes[1].uri=${AUTH_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/oauth2/**

spring.cloud.gateway.routes[2].id=auth-login-oauth2
spring.cloud.gateway.routes[2].uri=${AUTH_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/login/oauth2/**

# QUANTITY SERVICE
spring.cloud.gateway.routes[3].id=quantity-service
spring.cloud.gateway.routes[3].uri=${QUANTITY_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/quantity/**

# HISTORY SERVICE
spring.cloud.gateway.routes[4].id=history-service
spring.cloud.gateway.routes[4].uri=${HISTORY_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/history/**

# =========================
# LOGGING
# =========================
logging.level.org.springframework.cloud.gateway=INFO

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =========================
# SWAGGER ROUTES
# =========================

# AUTH SWAGGER
spring.cloud.gateway.routes[5].id=auth-swagger
spring.cloud.gateway.routes[5].uri=${AUTH_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[5].predicates[0]=Path=/auth/v3/api-docs
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/auth/v3/api-docs, /v3/api-docs

# QUANTITY SWAGGER
spring.cloud.gateway.routes[6].id=quantity-swagger
spring.cloud.gateway.routes[6].uri=${QUANTITY_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[6].predicates[0]=Path=/quantity/v3/api-docs
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/quantity/v3/api-docs, /v3/api-docs

# HISTORY SWAGGER
spring.cloud.gateway.routes[7].id=history-swagger
spring.cloud.gateway.routes[7].uri=${HISTORY_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[7].predicates[0]=Path=/history/v3/api-docs
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/history/v3/api-docs, /v3/api-docs

# =========================
# SWAGGER UI CONFIG
# =========================
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=quantity-service
springdoc.swagger-ui.urls[1].url=/quantity/v3/api-docs

springdoc.swagger-ui.urls[2].name=history-service
springdoc.swagger-ui.urls[2].url=/history/v3/api-docs

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true