### Database Configuration
#db.url=jdbc:mysql://localhost:3306/quantity_measurement_db
#db.username=root
#db.password=AnushkaSinghal24
#db.driver=com.mysql.cj.jdbc.Driver
#
## Connection Pool
#db.pool.size=10
#
## Repository type
#repository.type=database
#
## App Name
#spring.application.name=quantity-measurement-app
#
## MySQL Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db
#spring.datasource.username=root
#spring.datasource.password=AnushkaSinghal24
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
## Server Port (optional)
#server.port=${8080}


# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Railway injects PORT dynamically ? this is required
server.port=${PORT:8080}

# Database (use Railway env var references)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
#
## GOOGLE OAUTH
#spring.security.oauth2.client.registration.google.client-id=CLIENT_ID;
#spring.security.oauth2.client.registration.google.client-secret=CLIENT_SECRET;
#
#spring.security.oauth2.client.registration.google.scope=email,profile