# Database Configuration
db.url=jdbc:mysql://localhost:3306/quantity_measurement_db
db.username=root
db.password=AnushkaSinghal24
db.driver=com.mysql.cj.jdbc.Driver

# Connection Pool
db.pool.size=10

# Repository type
repository.type=database